apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-api
    context: ./src
    sync:
      manual:
      - src: api/src/**/*
        dest: .
      - src: common/**/*
        dest: .
    docker:
      dockerfile: api/Dockerfile.dev
      buildArgs:
        SCRIPT: '{{.SCRIPT}}'
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-go
    context: ./src/go
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        SCRIPT: '{{.SCRIPT}}'
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-frontend
    context: ./src
    docker:
      dockerfile: frontend/Dockerfile.dev
      buildArgs:
        SCRIPT: "{{.SCRIPT}}"
    sync:
      manual:
      - src: 'frontend/src/**/*.ts'
        dest: .
      - src: common/**/*
        dest: .
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml

