apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-api
    context: ./api
    sync:
      manual:
      - src: src/**/*
        dest: .
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        SCRIPT: '{{.SCRIPT}}'
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-go
    context: ./go
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        SCRIPT: '{{.SCRIPT}}'
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml
  # - image: gcr.io/k8s-skaffold/frontend
  #   context: ./frontend
  #   docker:
  #     dockerfile: Dockerfile.dev
  #     buildArgs:
  #       SCRIPT: "{{.SCRIPT}}"
  #   sync:
  #     manual:
  #     - src: 'src/**/*.ts'
  #       dest: .
  
