apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-api
    context: ./api
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        SCRIPT: "{{.SCRIPT}}"
    sync:
      manual:
      - src: 'src/**/*'
        dest: .
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-go
    context: ./go
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        SCRIPT: "{{.SCRIPT}}"

  # - image: gcr.io/k8s-skaffold/frontend
  #   context: ./frontend
  #   docker:
  #     dockerfile: Dockerfile.dev
  #     buildArgs:
  #       SCRIPT: "{{.SCRIPT}}"
  #   sync:
  #     manual:
  #     - src: 'src/**/*.ts'
  #       dest: .
deploy:
  kubectl:
    manifests:
    - "./k8s/*.yaml"
