apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/api
    context: ./api
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        SCRIPT: "{{.SCRIPT}}"
    sync:
      manual:
      - src: 'src/**/*.ts'
        dest: .

  # - image: gcr.io/k8s-skaffold/frontend
  #   context: ./frontend
  #   docker:
  #     dockerfile: Dockerfile.dev
  #     buildArgs:
  #       SCRIPT: "{{.SCRIPT}}"
  #   sync:
  #     manual:
  #     - src: 'src/**/*.ts'
  #       dest: .
deploy:
  kubectl:
    manifests:
    - "./k8s/*.yaml"
