apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-api
    context: .
    sync:
      manual:
      - src: src/api/src/**/*
        dest: .
      - src: src/common/**/*
        dest: .
    docker:
      dockerfile: src/api/Dockerfile.dev
      buildArgs:
        SCRIPT: '{{.SCRIPT}}'
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-go
    context: ./src/go
    docker:
      dockerfile: Dockerfile.dev
      buildArgs:
        SCRIPT: '{{.SCRIPT}}'
  - image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-frontend
    context: .
    docker:
      dockerfile: src/frontend/Dockerfile.dev
      buildArgs:
        SCRIPT: "{{.SCRIPT}}"
    sync:
      manual:
      - src: src/frontend/src/**/*
        dest: .
      - src: src/common/**/*
        dest: .
deploy:
  kubectl:
    manifests:
    - ./k8s/*.yaml

