apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-workdir
  namespace: cicd
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: efs
  resources:
    requests:
      storage: 4Gi