apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cicd
  labels:
    app: api
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: cicd-service-account
      containers:
      - name: api
        image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-api
        volumeMounts:
          - name: workdir-volume
            mountPath: /opt/backend/workdir
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: http-websocket
            containerPort: 8081
            protocol: TCP
      volumes:
        - name: workdir-volume
          persistentVolumeClaim:
            claimName: pvc-workdir