apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
  namespace: cicd
  labels:
    app: go
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: 365165116898.dkr.ecr.eu-west-1.amazonaws.com/skaffold-go
        ports:
          - name: http
            containerPort: 7777
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: cicd
spec:
  selector:
    app: go
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777