FROM node:10-alpine

RUN apk add --no-cache git

ARG SCRIPT
ENV SCRIPT ${SCRIPT}
WORKDIR /opt/backend
EXPOSE 3000

ADD api/package.json .
ADD api/package-lock.json .
RUN npm install

COPY ./api/tsconfig.json ./
COPY ./api/webpack.config.js ./
COPY ./api/src ./src
COPY ./common ./common

CMD npx webpack --watch
