FROM node:8.12.0-alpine

ARG SCRIPT
ENV SCRIPT ${SCRIPT}
WORKDIR /opt/frontend
EXPOSE 3000
CMD ["npm", "start"]

COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm install


COPY ./frontend/tsconfig.json ./
COPY ./frontend/src ./src
COPY ./frontend/public ./public
COPY ./common ./common
