FROM golang:1.11

WORKDIR /usr/backend

COPY ./go.mod .
COPY ./go.sum .

RUN go mod download

COPY ./main.go .
COPY ./api ./api
COPY ./protos ./protos

# Run the executable
CMD ["go", "run", "main.go"]
