FROM node:10-alpine

RUN apk add --no-cache git

ARG SCRIPT
ENV SCRIPT ${SCRIPT}
WORKDIR /opt/backend
EXPOSE 3000

ADD package.json .
ADD package-lock.json .
RUN npm install

COPY ./main.js ./
COPY ./tsconfig.json ./
COPY ./.babelrc ./
COPY ./src ./src

CMD ["node", "main"]