FROM node:10-alpine

RUN apk add --no-cache git

ARG SCRIPT
ENV SCRIPT ${SCRIPT}
WORKDIR /opt/backend
EXPOSE 3000

ADD package.json .
ADD package-lock.json .
RUN npm install

COPY ./tsconfig.json ./
COPY ./webpack.config.js ./
COPY ./src ./src

CMD npx webpack --watch